#!/bin/bash

echo '$1 = ' $1
JournalDirectory='/home/daedalus/Documents/self_log/'

Date=$(date +%Y/%m/%d)


File_Path="$JournalDirectory$Date/"


File=$File_Path$1


if [ -e "$File" ]; then
    echo "$File exists"
    /snap/bin/vscode -n $File
else
    echo "ERROR: $File does not exists"
fi
