#!/bin/bash



echo '$1 = ' $1

Date=$(date +%Y/%m/%d)


File_Path="$HOME/Documents/self_log/$Date/"


File=$File_Path$1

#alias md_editor=$(urxvt -e "kak" "$File")
#alias md_editor=$(code-oss -n "$File")

echo "$File"

if [ -e "$File" ]; then
    echo "$File exists"
    gedit --new-window "$File" &
else
    echo "ERROR: $File does not exists"
fi
