#!/bin/zsh



Date=$(date +%Y/%m/%d)
#the Self log directory is stored in my zsh config
Created_Path="$SLog_directory$Date"

mkdir -p $Created_Path

Insert_Date=$(date +"%A %m/%d/%Y")

for file in templates/*.md; do
    word_to_be_removed="_template"
    study="Study"
    created_file=$(echo $(basename "${file%.*}") )
    created_file="${created_file//$word_to_be_removed/}.md"
    if [[ ${created_file} != *"Study"* ]] && [[ ${created_file} != *"decision"* ]]; then
      cp -n "$file" "$Created_Path/$created_file"
      echo "$Created_Path/$created_file"
      sed -i "s@\[REPLACE\]@$Insert_Date@" "$Created_Path/$created_file"
    fi
done
