#!/bin/bash

JournalDirectory='/home/daedalus/Documents/self_log/'
TemplateDirectory='/home/daedalus/github/daily_practice/templates/'
Date=$(date +%Y/%m/%d)

Created_Path="$JournalDirectory$Date"

mkdir -p $Created_Path



for file in $TemplateDirectory*.md; do
    word_to_be_removed="_template"
    study="Study"
    created_file=$(echo $(basename "${file%.*}") )
    created_file="${created_file//$word_to_be_removed/}.md"
    if [ $created_file == *"Study"* ]; then
      *cp -n "$file" "$Created_Path/$created_file"
    fi
done
