#!/bin/bash

daily_files=(`cat list/daily.txt`)

Date=$(date +%Y/%m/%d)
#the Self log directory is stored in my zsh config
Created_Path="$HOME/Documents/self_log/$Date"


printenv

mkdir -p $Created_Path

Insert_Date=$(date +"%A %m/%d/%Y")

for template in "${daily_files[@]}"; do
    word_to_be_removed="_template"
    created_file=${template/$word_to_be_removed}
    if [[ ${created_file} != *"Study"* ]] && [[ ${created_file} != *"decision"* ]]; then
      cp -n "templates/$template" "$Created_Path/$created_file"
      echo "$Created_Path/$created_file"
      sed -i "s@\[REPLACE\]@$Insert_Date@" "$Created_Path/$created_file"
    fi
done
