#!/bin/bash

SystemDirectory='/etc/systemd/system/'


service_list=()
timer_list=()



for file in timers/*.timer; do
  echo $file
  if [[ $file != *"template"* ]]; then
      base_name=$(echo $(basename "${file%.*}") )
      base_file=$(echo $(basename "${file}") )
      echo $base_file
      service_list+=( $base_name)
      timer_list+=( $base_file)
      cp -i timers/$base_file $SystemDirectory$base_file
  fi
done

for file in services/*.service; do
  if [[ $file != *"template"* ]]; then
      base_file=$(echo $(basename "${file}") )
      echo $base_file
      cp -i services/$base_file $SystemDirectory$base_file
  fi
done

for file in slices/*.slice; do
  if [[ $file != *"template"* ]]; then
      base_file=$(echo $(basename "${file}") )
      echo $base_file
      cp -i slices/$base_file $SystemDirectory$base_file
  fi
done

echo ${service_list[*]}

systemctl stop ${service_list[*]}

systemctl daemon-reload

systemctl enable ${timer_list[*]}

systemctl start ${service_list[*]}